### ISSUE TITLE
Uncaught SyntaxError: Unexpected token '<'

### ISSUE THREAD

**Issue by ogulcancelik** [Valmoz/gae-vue-flask-starter#8]
Hi there,

Thanks for this really cool template, I'm trying to convert my GAE app to Flask, so I tried this template with a fresh install first, with serve command it looks great, it can redirect request.

However, when I try with built Vue app; after setting GAE_ENV to standard in my local environment with `export GAE_ENV=standard` , the page loads as blank page and gives this error 
`Uncaught SyntaxError: Unexpected token '<'`
any idea why?

**Comment by valmoz** [comment]
Hi, why are you setting the GAE_ENV variable? where are you using it?

By the way, it seems that it cannot recognize some file the app is trying to load, for example the index.html used to load the whole app or one of the templates. Are you trying to use the built app locally or on GAE?

**Comment by ogulcancelik** [comment]
I'm trying to test how it works with built Vue.js app, so I'm using GAE_ENV variable to mimic GAE and make Flask render built index.html rather than urllib line, if it makes sense. Also its a fresh clone, didnt add anything.

**Comment by valmoz** [comment]
The following code is needed because Vue.js needs a HTML server to be executed properly, and I'm not sure that if executed locally flask will be able to act properly.
`def vue_client(path):
    logging.info(path)
    if os.getenv('GAE_ENV', '').startswith('standard'):
        return render_template('index.html')
    else:
        url = 'http://localhost:3000/{0}'.format(path)
        logging.error(url)
        return urllib.request.urlopen(url).read()`
I think you can try to check if flask is actually trying to access the correct file. Are you serving the index.html contained into the app/dist folder? you could try to put an absolute path in the render template line, just to be sure.

**Comment by ogulcancelik** [comment]
Of course that code is there, as I said it's a fresh clone from the repo. So after exporting GAE_ENV as standard, `return render_template('index.html')` executes and it tries to render index.html from the app/dist folder. the built app is there so there shouldn't be any problem but somehow console gives the `Uncaught SyntaxError: Unexpected token '<'` error, so flask renders properly but vue cant find js files.. I think?

**Comment by valmoz** [comment]
Ok the problem is not on index.html file, but on the JS files as you said.
The render_template instruction is called for every path, not only for the root '/'. This means that it is loading the index.html file instead of the JS files.
This doesn't happen when deployed on GAE because the app.yaml  file makes possible to bypass flask and to return directly the static files, so this code works perfectly on GAE but not locally.
If you want to load your app locally without serve, you must modify the code and return the proper static files when needed, checking the requested path and understanding when it is needed to load a file instead of rendering the index.html template.

**Comment by ogulcancelik** [comment]
Hmm, interesting. Okay, so If I want to test build Vue.js files and host them via Flask locally, I have to render js files accordingly. Gotcha!
Well, don't _really_ need to test it actually, I just wanted to see. So...
Thanks for the repository again,  I'm closing the issue :+1:
